const items = 
[
    {
        name: "flashlight",
        price: 200,
        tier: 1,
        maxAmmount: 3,
        added: 0,
        consumable: false,
        forced: true,
        forcedTier: 1,
        moneyMultiplier: 1.5,
        currentPrice: 200,

    },
    {
        name: "D.O.T.S projector",
        price: 400,
        tier: 1,
        maxAmmount: 1,
        added: 0,
        cosnumable: false,
        forced: true,
        forcedTier: 1,
        moneyMultiplier: 3,
        currentPrice: 400,

    },
    {
        name: "EMF reader",
        price: 100,
        tier: 1,
        maxAmmount: 1,
        added: 0,
        consumable: false,
        forced: true,
        forcedTier: 1,
        moneyMultiplier: 2,
        currentPrice: 100,
    },
    {
        name: "ghost writing book",
        price: 50,
        tier: 1,
        maxAmmount: 1,
        added: 0,
        consumable: false,
        forced: true,
        forcedTier: 1,
        moneyMultiplier: 1.5,
        currentPrice: 50,
    },
    {
        name: "spirit box",
        price: 50,
        tier: 1,
        maxAmmount: 1,
        added: 0,
        consumable: false,
        forced: true,
        forcedTier: 1,
        moneyMultiplier: 2,
        currentPrice: 50,

    },
    {
        name: "thermometer",
        price: 30,
        tier: 1,
        maxAmmount: 1,
        added: 0,
        consumable: false,
        forced: true,
        forcedTier: 1,
        moneyMultiplier: 1.2,
        currentPrice: 30,

    },
    {
        name: "uv light",
        price: 35,
        tier: 1,
        maxAmmount: 1,
        added: 0,
        consumable: false,
        forced: true,
        forcedTier: 1,
        moneyMultiplier: 1.6,
        currentPrice: 35,
    },
    {
        name: "video camera",
        price: 50,
        tier: 1,
        maxAmmount: 3,
        added: 0,
        consumable: false,
        forced: true,
        forcedTier: 1,
        moneyMultiplier: 3,
        currentPrice: 50,

    },
    {
        name: "tripod",
        price: 25,
        tier: 1,
        maxAmmount: 4,
        added: 0,
        consumable: false,
        forced: false,
        moneyMultiplier: 1.5,
        currentPrice: 25,
    },
    {
        name: "crucifix",
        price: 30,
        tier: 1,
        maxAmmount: 2,
        added: 0,
        consumable: true,
        forced: false,
        moneyMultiplier: 2.4,
        currentPrice: 30,
    },
    {
        name: "firelight",
        price: 15,
        tier: 1,
        maxAmmount: 4,
        added: 0,
        consumable: true,
        forced: false,
        moneyMultiplier: 1.3,
        currentPrice: 15,
    },
    {
        name: "incense",
        price: 15,
        tier: 1,
        maxAmmount: 4,
        added: 0,
        consumable: true,
        forced: false,
        moneyMultiplier: 1.2,
        currentPrice: 15,
    },
    {
        name: "igniter",
        price: 10,
        tier: 1,
        maxAmmount: 4,
        added: 0,
        consumable: true,
        forced: false,
        moneyMultiplier: 1.1,
        currentPrice: 10,
    },
    {
        name: "head gear",
        price: 60,
        tier: 1,
        maxAmmount: 4,
        added: 0,
        consumable: false,
        forced: false,
        moneyMultiplier: 1.7,
        currentPrice: 60,
    },
    {
        name: "motion sensor",
        price: 100,
        tier: 1,
        maxAmmount: 4,
        added: 0,
        consumable: false,
        forced: false,
        moneyMultiplier: 2.3,
        currentPrice: 100,
    },
    {
        name: "parabolic microphone",
        price: 50,
        tier: 1,
        maxAmmount: 2,
        added: 0,
        cosnumable: false,
        forced: true,
        moneyMultiplier: 1.6,
        currentPrice: 50,
    },
    {
        name: "photo camera",
        price: 40,
        tier: 1,
        maxAmmount: 3,
        added: 0,
        consumable: false,
        forced: false,
        moneyMultiplier: 2,
        currentPrice: 40,
    },
    {
        name: "salt",
        price: 15,
        tier: 1,
        maxAmmount: 3,
        added: 0,
        consumable: true,
        forced: false,
        moneyMultiplier: 1.5,
        currentPrice: 15,
    },
    {
        name: "sanity medication",
        price: 20,
        tier: 1,
        maxAmmount: 4,
        added: 0,
        consumable: true,
        forced: false,
        moneyMultiplier: 2.4,
        currentPrice: 20,
    },
    {
        name: "sound sensor",
        price: 80,
        tier: 1,
        maxAmmount: 4,
        added: 0,
        consumable: false,
        forced: false,
        moneyMultiplier: 1.4,
        currentPrice: 80,
    }

]